#!/bin/bash
# scaffold - generate two Docker Microservices (Express RESTful application & Postgres DB skeleton)
# Usage: scafoold <resource> [ModelName] <github/docker-username>
# e.g. scaffold planets Planet emilesherrott

set -e  # Stop script imeediately if any command fails

resource="$1"
model="${2:-${resource^}}"
username="$3"

# Guard: we must have a resource name or the script should fail immediately
if [ -z "$resource" ]; then
  echo "Usage: scaffold <resource> [ModelName] <github/docker-username>" >&2
  echo "e.g. scaffold planets Planet emilesherrott" >&2
  exit 1
fi

# Guard: we must have the Docker username to successfully scaffold docker-compose.yml file
if [ -z "$username" ]; then
  echo "Usage: scaffold <resource> [ModelName] <github/docker-username>" >&2
  echo "e.g. scaffold planets Planet emilesherrott" >&2
  exit 1
fi

log() { echo "[scaffold] $1"; }

log "Creating app for resource '$resource' (model '$model')"

# The three main subfolders for Docker Microservices and IAC in one loop
for dir in db server terraform; do
  mkdir -p "$dir"
done


# The four sub-folders under server/. made in one loop
for dir in controllers db models routers; do
  mkdir -p "server/$dir"
done

# The main files in the root of the repository

# README.md
cat > README.md << EOF
# ${resource} API

A small Express MVC API for ${resource}, generated by the scaffold script.

## Getting started

\`\`\`
npm install
npm run setupDb
npm start
\`\`\`
EOF


# docker-compose.yml
cat > docker-compose.yml << EOF
services:
  ${resource}-mvc:
    image: ${username}/${resource}-mvc-cloud:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - ${resource}-db
    networks:
      - ${resource}-network

  # The value of 'DB_HOST' we reference in the MVC Dockerfile  
  ${resource}-db:
    image: ${username}/${resource}-db-cloud:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - ${resource}-network
      
networks:
  ${resource}-network:
EOF

# .gitignore
cat > .gitignore << 'EOF'
# Node
node_modules/
.env

# OS / editor
.DS_Store
.vscode/

# Terraform
.terraform/
*.tfstate
*.tfstate.*
*.tfvars
*.tfplan
EOF


# Jenkinsfile
cat > Jenkinsfile << 'EOF'
pipeline {
    agent any

    stages {
        stage('Docker Login') {
            steps {
                echo "Docker Login"
            }
        }
        stage('Build Docker Images') {
            steps {
                echo "Build Docker Images"
            }
        }
        stage('Push Docker Images') {
            steps {
                echo "Push Docker Images"
            }
        }
        stage('Terraform') {
            steps {
                echo "Terraform"
            }
        }
    }
}
EOF

log "Created package.json, README.md, docker-compose.yml, .gitignore and Jenkins File"





# Making the core files of DB


# Dockerfile
cat > db/Dockerfile << EOF
FROM postgres
ENV POSTGRES_PASSWORD=docker
ENV POSTGRES_DB="${resource}"
COPY "${resource}".sql /docker-entrypoint-initdb.d/
EOF


# SQL
cat > db/"${resource}".sql << EOF
DROP TABLE IF EXISTS ${resource};

CREATE TABLE ${resource} (
  id INT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO ${resource} (name) VALUES ('Example one'), ('Example two');
EOF


# .dockerignore
cat > db/.dockerignore << 'EOF'
.git
.gitignore
.github

node_modules
**/node_modules

.env

terraform/.terraform
terraform/*.tfstate
terraform/*.tfstate.*
terraform/*.tfplan

README.md
.DS_Store
.vscode
EOF





# Making the core files of API


# Dockerfile
cat > server/Dockerfile << EOF
FROM node:24
WORKDIR /app
COPY package*.json /app
RUN npm install
COPY . /app
ENV PORT=80
ENV DB_USER=postgres
ENV DB_HOST=${resource}-db
ENV DB_NAME=${resource}
ENV DB_PASSWORD=docker
ENV DB_PORT=5432
EXPOSE 80
CMD ["node", "index.js"]
EOF


# .dockerignore
cat > server/.dockerignore << 'EOF'
.git
.gitignore
.github

node_modules
**/node_modules

.env

terraform/.terraform
terraform/*.tfstate
terraform/*.tfstate.*
terraform/*.tfplan

README.md
.DS_Store
.vscode
EOF


# server/package.json
cat > server/package.json << EOF
{
  "name": "${resource}-api",
  "version": "1.0.0",
  "main": "server/index.js",
  "scripts": {
    "start": "node server/index.js",
    "setupDb": "node server/db/setup.js"
  },
  "dependencies": {
    "express": "^4.19.2",
    "pg": "^8.11.5",
    "cors": "^2.8.5",
    "dotenv": "^16.0.3"
  },
  "devDependencies": {
    "nodemon": "^3.1.14"
  }
}
EOF


# server/index.js
cat > server/index.js << 'EOF'
const app = require("./app");

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Listening on port ${PORT}`));
EOF


# server/app.js
cat > server/app.js << EOF
const express = require("express");
const cors = require("cors");
const ${resource}Router = require("./routers/${resource}");

const app = express();
app.use(cors());
app.use(express.json());

app.use("/${resource}", ${resource}Router);

module.exports = app;
EOF

log "Created server/index.js and server/app.js"


# Controller
cat > server/controllers/${resource}.js << EOF
const ${model} = require("../models/${model}");

async function index(req, res) {
  const rows = await ${model}.findAll();
  res.json(rows);
}

module.exports = { index };
EOF


# Router
cat > server/routers/${resource}.js << EOF
const express = require("express");
const controller = require("../controllers/${resource}");

const router = express.Router();
router.get("/", controller.index);

module.exports = router;
EOF


# Model
cat > server/models/${model}.js << EOF
const db = require("../db/connect");

class ${model} {
  static async findAll() {
    const result = await db.query("SELECT * FROM ${resource}");
    return result.rows;
  }
}

module.exports = ${model};
EOF

log "Created controller, router and model"





# DB Connection
cat > server/db/connect.js << 'EOF'
const { Pool } = require('pg');

const db = new Pool({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port: process.env.DB_PORT || 5432,
});

module.exports = db;
EOF

log "Created db/connect.js"





# Terraform IAAC

# The main folders for a Terraform project
for dir in backend infrastructure; do
  mkdir -p terraform/"$dir"
done

# terraform/backend/main.tf
cat > terraform/backend/main.tf << 'EOF'
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
EOF


# Main infrastructure setup
for file in main variables data-providers network-card network-security-group outputs; do
  touch terraform/infrastructure/"$file".tf
done

# terraform/infrastructure/main.tf
cat > terraform/infrastructure/main.tf << 'EOF'
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
EOF





# Creating Git Repo

git init 
git branch -m main
git add .
git commit -m "Initial commit"

gh repo create "${username}/${resource}-backend" \
  --public \
  --source=. \
  --remote=origin \
  --push





# Initial Docker Build & Push

# Built for local use on my M1 Apple Silicon
docker build -t "${username}"/"${resource}"-db:latest ./db
docker build -t "${username}"/"${resource}"-mvc:latest ./server

# Build for Azure use with x86_64/amd64 architecture
docker build --platform linux/amd64 -t "${username}"/"${resource}"-db-cloud:latest ./db
docker build --platform linux/amd64 -t "${username}"/"${resource}"-mvc-cloud:latest ./server

# Only push cloud compatible images
docker push "${username}"/"${resource}"-db-cloud:latest
docker push "${username}"/"${resource}"-mvc-cloud:latest


log "Done. Run 'tree' to see your new structure."